INSERT INTO PERFIL (id,nome) VALUES(1,'RH');
INSERT INTO PERFIL (id,nome) VALUES(2,'FUNCIONARIO');
INSERT INTO USER_MODEL(id,email,nome,pass) VALUES(1,'robsonlangkammer@hotmail.com','ROBSON','$2a$10$nYe.ZnL.eSH14p1mrMTHoOeZJWbHTwpdbvr3hI8.FN1WLom0lQwGy');
INSERT INTO USER_MODEL(id,email,nome,pass) VALUES(2,'administrador.ferias@castgroup.com.br','TESTE DO SISTEMA','$2a$10$Bb/GOOY1kHGEgZHdGxNidOAh0u54BgJkH5BBydyIWKwrIlhrndFnO');
INSERT INTO USER_MODEL_PERFIL(USER_MODEL_ID, PERFIL_ID ) VALUES (1,1);
INSERT INTO USER_MODEL_PERFIL(USER_MODEL_ID, PERFIL_ID ) VALUES (2,1);
